bazel-contrib/rules-template

.github/workflows/ci.bazelrc, .github/workflows/ci.yaml, .github/workflows/release.yml, README.md
@alexeagle
Github actions caches don't update already existing caches, so the cache that gets loaded could be old. This sets a new cache using a cache key derived from a hash of files. The use of `restore-keys: bazel-cache-` will find the most recent cache stored scoped to this branch or a parent branch.
=> build: fix ci cacheing to use recently built caches

.github/workflows/workspace_snippet.sh
`rules_mylang_dependencies` is actually in `mylang/repositories.bzl`, not `mylang/dependencies.bzl` (which doesn't exist)
=> Fix workspace snippet

.github/workflows/workspace_snippet.sh, internal_deps.bzl
Required per https://github.com/bazel-contrib/SIG-rules-authors/issues/11
=> chore: Update github archive URLs to have stable SHAs

mylang/private/toolchains_repo.bzl
Typically we expect rules fetch toolchains for use during actions, so the toolchain selection should be based on the execution platform.
It's possible that tools may need to run on the target platform, but rulesets could still declare a second toolchain constrained by the target.
The code here is incorrect, as when the exec platform differs from the target platform, toolchain selection will find *no* matching toolchain
=> Declare toolchain only constrained by the exec platform

.gitignore
Adds the standard `.idea` folder and the `.ijwb` created when used with the bazel plugin to the `.gitignore` folder in the template.
=> feat: add IntelliJ IDE folders to .gitignore

internal_deps.bzl
This is unused within the template
=> chore(deps): remove bazel-integration-testing

.pre-commit-config.yaml
The default version of node that pre-commit downloads uses a very new version of GLIBC so set the default to an older version that will be more widely supported.
=> Pin version of node to one supported on ubuntu 18.04.

.bazelversion, .github/workflows/ci.yaml, WORKSPACE, docs/rules.md, internal_deps.bzl, mylang/defs.bzl
Also adds the GH actions code to cancel previous CI runs for a PR (same as https://github.com/aspect-build/rules_js/pull/694) and to run `test.sh` if that is found at the root of the matrix folder. This is a simple and robust way to run e2e tests that need to make multiple bazel invocations or do other work besides `bazel test ...`
=> Update internal_deps to latest and test with Bazel 6.0.0rc4 as well as Bazel 5.3.2

.github/workflows/ci.yaml, .github/workflows/release.yml
Using quotes for the items in path does not resolve `~` correctly and
thus leads to the following warning in the post section:
```
Warning: Path Validation Error: Path(s) specified in the action for
caching do(es) not exist, hence no cache is being saved.
```
=> Fix usage of GitHub actions cache

.github/workflows/release.yml, .github/workflows/workspace_snippet.sh
GitHub had promised that their source archives would have stable checksums, but then there was a big Bazel outage yesterday due to their changing it. Even if they do make such a guarantee and stick to it, we also have the problem that GitHub doesn't give download metrics on their source archive so this is still worth changing.
=> chore: publish release artifact

README.md
Links to the new GitHub blog post about stability of the sha
=> chore: document how to depend on HEAD

.github/workflows/ci.yaml, .github/workflows/release.yml
Reduces the amount of code that a fork of this repo ends up maintaining
=> chore: use reusable release workflow

.github/workflows/ci.bazelrc, .github/workflows/ci.yaml
Closes https://github.com/bazel-contrib/rules-template/issues/76
Depends on https://github.com/bazel-contrib/.github/pull/7
Disables the Bazel repository cache. See #76 for motivation.
=> Remove the Bazel repository cache

renovate.json
Configure Renovate to disable updates for the ruleset, but allow updates for example and test workspaces.
Related to https://github.com/bazel-contrib/SIG-rules-authors/discussions/82.
=> chore: update Renovate config with recommended ruleset settings

.github/workflows/release_prep.sh, MODULE.bazel
This avoids the need for Publish To BCR to create patch files like https://github.com/bazel-contrib/publish-to-bcr/pull/28 and reduces the clutter of `module_dot_bazel.patch` files in BCR
=> feat: stamp the version into the artifact

.github/workflows/release_prep.sh, MODULE.bazel
It doesn't work with Publish to BCR app's parsing of the file, and it's not important enough to spend time fixing that.
=> Revert release automation tagging

.github/workflows/release_prep.sh
Shows how ruleset authors can make smaller release artifacts.
=> feat(release): exclude examples/ folder by default

MODULE.bazel
Previously (keith/buildifier-prebuilt#68), buildifier CI checks will fail on Windows by default because the lack of Windows support for rule `buildifier_prebuilt`. This PR bumps `buildifier_prebuilt` to the version that supports Windows to fix this problem.
=> chore(deps): update buildifier_prebuilt for CI to succeed on Windows

.gitattributes, .github/workflows/release_prep.sh, README.md
Illustrate how to stamp the version into the release artifact as well, which we've needed in only a couple of rulesets. Makes it match bazelbuild/rules_proto#189
=> refactor: move 'git archive' config to .gitattributes

.bcr/presubmit.yml
Related https://github.com/bazelbuild/bazel-central-registry/discussions/1332
=> Set default Bazel versions to be tested

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md
This makes contributing to projects forked from this template more intuitive and require no manual local setup.
=> Add and document minimal devcontainers setup

README.md
This step is not needed, because the cache is already managed by [`bazel-contrib/.github/.github/workflows`](https://github.com/bazel-contrib/.github/tree/master/.github/workflows)
=> docs: remove unnecessary step

README.md
this is useful, since most tools like `grep` or `rg` search case insensitive by default
=> docs: explicitly list all locations to replace

e2e/smoke/BUILD
Set `@` before the replaceable name in the `load` call within the `BUILD` of the Smoke tests.
=> fix(e2e): set namespace prefix

.github/workflows/release_prep.sh
=> chore: improve bzlmod install instructions

.github/workflows/release.yml
This is a known issue documented in https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
Fixes #64
=> Give the releaser write permissions to the repo.

README.md
=> docs: Document how to ship pre-built tools

.github/workflows/ci.yaml
GitHub actions matrix "test" gets expanded to many status checks, making it impossible to keep the branch protection settings in the GitHub UI up-to-date as the matrix cells are updated.
This provides a "conclusion" status which can be used instead. Thanks @mattmoor for the code!
Demo: https://github.com/bazel-contrib/rules-template/actions/runs/9783272801/job/27011588324?pr=124
=> feat: provide stable-named job for branch protection

mylang/private/resolved_toolchain.bzl
This is unused and toolchain transitions have been the default a while now and has been removed in bazel.
See: https://github.com/keith/bazel/commit/43d0f9683935e9886bb05dcc42ac83d6593ac205
cc @katre
=> Remove incompatible_use_toolchain_transition

.github/workflows/release_prep.sh
Otherwise it picks up `main` when the GITHUB_REF is based on a cron trigger
=> fix(cd): script uses the supplied tag

.devcontainer/devcontainer.json, .github/workflows/ci.yaml, .pre-commit-config.yaml, README.md, renovate.json
Since the rules already prvide a pre-commit config, we should also make sure the checks pass CI and hooks stay up to date.
=> ci(pre-commit): Enable pre-commit CI and renovate

.github/workflows/publish.yaml, .github/workflows/release.yaml, .github/workflows/tag.yaml
Includes attestations for provenance of release artifacts
=> feat: use new Publish to BCR reusable workflow

.github/workflows/tag.yaml
Without this I am running into:
```
.github/workflows/tag.yaml:41:48: property "new-tag-version-type" is not defined in object type {new-tag: string; new-tag-version: string} [expression]
```
=> fix: Add new-tag-version-type as an output to the tag job before referring it from release

.github/workflows/tag.yaml
My earlier logic here releases a ruleset twice a month.
However if it has been a long time since a release, and a new bugfix or feature has been merged, there's no reason to wait for up to 15 days.
Instead it's better for the cron to trigger frequently, and just skip tagging if there's already one recent enough.
=> fix: auto-tagging more promptly
